config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :restaurants, only: [:show]
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :meetings, only: [:index, :show, :destroy]
    resources :invitations, only: [:show, :new, :create, :destroy, :update, :index]
  end

  get '/signup', to: 'users#new', as: "signup"
  get '/login', to: 'sessions#new', as: "login"
  get '/logout', to: 'sessions#destroy', as: "logout"
  post '/sessions', to: 'sessions#create', as: "post_login"
  
  get '/admin', to: 'invitations#admin', as: 'admin'
  post '/invitations', to: 'invitations#create', as: 'create_invitations'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  email           :string
#  password_digest :string
#

class User < ActiveRecord::Base
  has_many :invitations
  has_many :availabilities
  has_many :guests
  has_many :meetings, through: :invitations
  has_many :restaurants, through: :meetings
  before_save :set_time_location, :set_photo
  has_secure_password
  validates_presence_of :name, :email, :password_digest, :birthdate
  validates :email, uniqueness: true

  def set_photo
    self.image = "http://api.randomuser.me/portraits/med/#{["men","women"].sample}/#{rand(1..35)}.jpg"
  end

  def set_time_location
    # belongs in a controller
    self.availabilities.build(time: "12", location:"10004") 
  end

  def accept_rate
    # move to sql
    accepted = self.invitations.select{|invitation| invitation.status == 'Accept'}.count
    invitations = self.invitations.count
    (accepted.to_f/invitations*100).round(2)
  end

  def age
    # use rails time operators to calculate
    date_hash = eval(self.birthdate)
    dob = DateTime.new(date_hash[1],date_hash[2],date_hash[3]) 
    now = Date.today
    age = ((now - dob) / 365.25).to_i
  end

  private
  # These methods are impressive
  def self.sort_array_by(user_array, attribute)
    user_array.sort_by do |user|
      user.availabilities.first.send(attribute)
    end
  end

  def self.time_filter(user_array)
    sorted_array = self.sort_array_by(user_array, 'time')
    sorted_array.chunk do |user|
      user.availabilities.first.time
    end.to_h.values
  end

  def self.location_filter(user_array)
    sorted_array = self.sort_array_by(user_array, 'location')
    sorted_array.chunk do |user|
      user.availabilities.first.location
    end.to_h.values
  end

  def self.apply_filters
    time_results = self.time_filter(User.all)
    location_results = time_results.map do |time_result|
      self.location_filter(time_result)
    end.flatten(1)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit] 
  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, :notice => "Thank you for signing up!"
    else
      render :new
    end
  end

  def show
    
  end

private
	def set_user
    @user = User.find(params[:id])
  end
    
  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation, :birthdate)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
    <%= f.label :birthdate %><br>
    <%= f.date_select :birthdate %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing your profile</h1>

<%= render 'form' %>

<%= link_to 'Show', user_path %> |
<%= link_to 'Back', user_path %>

app/views/users/new.html.erb
<header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Sign Up</h1>

				<%= render 'form' %>

				<%= link_to 'Back', root_path %>
            </div>
        </div>
</header>

app/views/users/show.html.erb
<img src=<%= @user.image %>>
<h2><%= @user.name.capitalize %></h2>
<p>Age: <%= @user.age%></p>
<p>
  <!-- use a view object for the logic in here -->
  <h4>Acceptance rate: <%= @user.accept_rate %>%</h4>
  <% if @user.invitations.count > 0 %>
    <% if @user.invitations.last.status == "pending" %>
      <%= link_to 'Pending Invitation!', user_invitation_path(@user, @user.invitations.last) %>
    <% else %>
      <% if @user.meetings.last.status == "pending" %>
        Waiting on lunch partner to respond.
      <% elsif @user.meetings.last.status == "declined" %>
        No pending invitations, please check back tomorrow.
      <% else %>
        <%= link_to "Today's Lunch", user_meeting_path(@user, @user.meetings.last) %>
      <% end %>
    <% end %>
  <% end %>
</p>
<p>
  <%= link_to 'My Lunches', user_meetings_path(@user) %>
</p>