config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :restaurants, only: [:show]
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :meetings, only: [:index, :show, :destroy]
    resources :invitations, only: [:show, :new, :create, :destroy, :update, :index]
  end

  get '/signup', to: 'users#new', as: "signup"
  get '/login', to: 'sessions#new', as: "login"
  get '/logout', to: 'sessions#destroy', as: "logout"
  post '/sessions', to: 'sessions#create', as: "post_login"
  
  get '/admin', to: 'invitations#admin', as: 'admin'
  post '/invitations', to: 'invitations#create', as: 'create_invitations'

end

app/models/invitation.rb
# == Schema Information
#
# Table name: invitations
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  status     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  meeting_id :integer
#

class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :meeting

  def change_status(new_status)
    self.status = new_status
    self.save
    self.meeting.change_meeting_status(self)
  end

  private

# These methods belong in a service object, which you will learn about later
# For now, would prefer they are moved to a controller

  def self.select_pairs
    pairs = User.apply_filters.each_with_object([]) do |filtered_group, pairs|
      # use a higher level iterator instead of a while loop
      while filtered_group.count > 1
        pairs << filtered_group.shuffle!.pop(2)
      end
    end
  end

  def self.create_invitations
    self.select_pairs.each do |pair|
      meeting = Meeting.new(status: "pending", time: pair[0].availabilities.first.time)
      meeting.save
      invite_one = Invitation.create(meeting: meeting, user: pair[0], status: "pending")
      invite_two = Invitation.create(meeting: meeting, user: pair[1], status: "pending")
    end
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
	def index
    @user = User.find(params[:user_id])
    @invitations = @user.invitations
  end

  def show
    # binding.pry
    # change to current user later if necessary
    @user = User.find(params[:user_id])
    @invitation = Invitation.find_by(id: params[:id])
    @meeting = @invitation.meeting
    @restaurant = @invitation.meeting.restaurant
    if @invitation
      render 'show'
    else
      redirect_to user_path(@user), :notice => "Sorry! No invitation today."
    end
	end

	def new

	end

	def create
    Invitation.create_invitations
    redirect_to admin_path
	end

	def destroy
		
	end

  def update
    invitation = Invitation.find(params[:id])
    invitation.change_status(params[:status])
    redirect_to user_path(params[:user_id])
  end

  def admin

  end

end

app/helpers/invitation_helper.rb
module InvitationHelper
end

app/views/invitations/admin.html.erb
<%= form_tag create_invitations_path do %>
  <%= submit_tag 'Send Invitations' %>
<% end %>

app/views/invitations/index.html.erb
<h1>Invitations</h1>
<% @invitations.each do |invitation| %>
  <p>Invitation id: <%= link_to invitation.id, user_invitation_path(current_user, invitation) %></p>
  <p>Status: <%= invitation.status %></p>
<% end %>
  

app/views/invitations/show.html.erb
<h1>Invitation</h1>
<p>To: <%= @user.name %> </p>

<%= render partial: 'layouts/restaurant', locals: {restaurant: @restaurant, meeting: @meeting } %>

<div>
  <% if @invitation.status == 'pending' %>
    <%= form_tag user_invitation_path(@user, @user.invitations.last), method: :patch do %>
      <%= submit_tag 'Accept', name: :status %>
      <%= submit_tag 'Decline', name: :status %>
    <% end %>
  <% else %>
    You chosen to <%= @invitation.status.downcase %> this invitation.
  <% end %>
</div>

<p><%= link_to 'Invitations', user_invitations_path(@user) %></p>