config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  resources :restaurants, only: [:show]
  resources :users, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :meetings, only: [:index, :show, :destroy]
    resources :invitations, only: [:show, :new, :create, :destroy, :update, :index]
  end

  get '/signup', to: 'users#new', as: "signup"
  get '/login', to: 'sessions#new', as: "login"
  get '/logout', to: 'sessions#destroy', as: "logout"
  post '/sessions', to: 'sessions#create', as: "post_login"
  
  get '/admin', to: 'invitations#admin', as: 'admin'
  post '/invitations', to: 'invitations#create', as: 'create_invitations'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Just Lunch</a>
    </div>


<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
                    <% if current_user %>
                    <li>
                        <%=link_to "#{current_user.name.capitalize}'s Profile",user_path(current_user) %>
                    </li>
                    <li>
                        <%=link_to "Log Out",logout_path %>
                    </li>
                    <li>
                    <div id ="headerpic">
                        <img src=<%= current_user.image %>>
                        </div>
                    </li>
                    <% else %>
                    <li>
                        <%=link_to "Sign Up", signup_path %>
                    </li>
                    <li>
                        <%=link_to "Log In", login_path %>
                    </li>
                    <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_restaurant.html.erb
	<h1><%= link_to restaurant.name, restaurant.url %></h1>
	<h4><%= meeting.created_at.strftime("%B %d, %Y") %> at <%= meeting.time %></h4>
  <hr>
	<img src=<%= restaurant.image %>>
<ul>
	<li>Cuisine: <%= restaurant.food %></li>
	<li>Location: <%= restaurant.location %></li>
	<li>Phone: <%= number_to_phone(restaurant.phone, area_code: true) %></li>
	<li>Rating: <%= restaurant.rating %> out of 5.</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustLunch</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render  "layouts/header" %>
 
<%= yield %>

</body>
</html>